//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactStudent
    {
        public string idStudent { get; set; }
        public string idCandidate { get; set; }
        public Nullable<System.DateTime> dateOfCall { get; set; }
        public string updating { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
