//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scolarship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scolarship()
        {
            this.StudentScolarships = new HashSet<StudentScolarship>();
            this.StudentVolunteers = new HashSet<StudentVolunteer>();
        }
    
        public int id { get; set; }
        public string ScolarshipName { get; set; }
        public Nullable<int> budgetScolarship { get; set; }
        public string admission { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentScolarship> StudentScolarships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentVolunteer> StudentVolunteers { get; set; }
    }
}
