//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentVolunteer
    {
        public string id { get; set; }
        public int ScolarshipSn { get; set; }
        public System.DateTime dateOfVolunteer { get; set; }
        public System.DateTime startHour { get; set; }
        public System.DateTime finishHour { get; set; }
        public string semester { get; set; }
    
        public virtual Scolarship Scolarship { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
