//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Active_Candidate_Info
    {
        public string idCandidate { get; set; }
        public Nullable<int> psychometric_grade { get; set; }
        public Nullable<int> worthy_of_advancement { get; set; }
        public Nullable<int> worthy_of_advancement_grade { get; set; }
        public Nullable<int> participation_heznek_highSchool { get; set; }
        public string highSchool_participation { get; set; }
        public Nullable<int> diagnosis_learning_disabilities { get; set; }
        public string reason_for_request { get; set; }
        public string general_life_story { get; set; }
        public Nullable<int> health_problems { get; set; }
        public string health_problems_deatails { get; set; }
        public Nullable<int> financial_difficulties { get; set; }
        public string financial_difficulties_details { get; set; }
        public Nullable<int> family_issues { get; set; }
        public string family_issues_details { get; set; }
        public Nullable<int> average_wage_father { get; set; }
        public Nullable<int> average_wage_mother { get; set; }
        public Nullable<int> disabilty_parents { get; set; }
    
        public virtual User_Profile User_Profile { get; set; }
        public virtual Organization_Frames_HighSchool Organization_Frames_HighSchool { get; set; }
    }
}
