//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Candidate
    {
        public string idScholar { get; set; }
        public string idCandidate { get; set; }
        public System.DateTime dateOfCall { get; set; }
        public string study_funding { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
    
        public virtual User_Profile User_Profile { get; set; }
        public virtual User_Profile User_Profile1 { get; set; }
    }
}
