//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Participant_Event = new HashSet<Participant_Event>();
        }
    
        public int sn { get; set; }
        public string nameEvent { get; set; }
        public string subjectEvent { get; set; }
        public Nullable<System.DateTime> eventDate { get; set; }
        public Nullable<System.TimeSpan> eventHour { get; set; }
        public string eventLocation { get; set; }
        public int typeOfParticipants { get; set; }
        public Nullable<int> numParticipantsExpected { get; set; }
        public Nullable<int> numOfActualParticipants { get; set; }
        public Nullable<int> participant_sn { get; set; }
    
        public virtual Groups Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant_Event> Participant_Event { get; set; }
    }
}
