//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public string nameOfFile { get; set; }
        public string idOfTheUploader { get; set; }
        public string fileLocation { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
