//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.Services.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HeznekDBEntities : DbContext
    {
        public HeznekDBEntities()
            : base("name=HeznekDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academic_Institut> Academic_Institut { get; set; }
        public virtual DbSet<Active_Candidate_Info> Active_Candidate_Info { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Contact_Candidate> Contact_Candidate { get; set; }
        public virtual DbSet<Deposits_Scholarship> Deposits_Scholarship { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<File> File { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Login_Permissions> Login_Permissions { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Organization_Frames_HighSchool> Organization_Frames_HighSchool { get; set; }
        public virtual DbSet<Participant_Event> Participant_Event { get; set; }
        public virtual DbSet<Scholarship> Scholarship { get; set; }
        public virtual DbSet<Scholarship_Student_Bank> Scholarship_Student_Bank { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Student_Scholarship> Student_Scholarship { get; set; }
        public virtual DbSet<Student_Volunteer> Student_Volunteer { get; set; }
        public virtual DbSet<Study_Field> Study_Field { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User_Profile> User_Profile { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
    }
}
