//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.Services.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HeznekDBEntities : DbContext
    {
        public HeznekDBEntities()
            : base("name=HeznekDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<academicInstitutTbl> academicInstitutTbl { get; set; }
        public virtual DbSet<bank> bank { get; set; }
        public virtual DbSet<cityTbl> cityTbl { get; set; }
        public virtual DbSet<contactScholarAndCandidate> contactScholarAndCandidate { get; set; }
        public virtual DbSet<deposits_scholarship> deposits_scholarship { get; set; }
        public virtual DbSet<@event> @event { get; set; }
        public virtual DbSet<files> files { get; set; }
        public virtual DbSet<loginAndPermissions> loginAndPermissions { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<organization_frames_highSchool> organization_frames_highSchool { get; set; }
        public virtual DbSet<participantInEvent> participantInEvent { get; set; }
        public virtual DbSet<scholar_bank_details> scholar_bank_details { get; set; }
        public virtual DbSet<scholarship> scholarship { get; set; }
        public virtual DbSet<serviceTbl> serviceTbl { get; set; }
        public virtual DbSet<statusTbl> statusTbl { get; set; }
        public virtual DbSet<studentScholarship> studentScholarship { get; set; }
        public virtual DbSet<studentVolunteer> studentVolunteer { get; set; }
        public virtual DbSet<studyFieldTbl> studyFieldTbl { get; set; }
        public virtual DbSet<userTbl> userTbl { get; set; }
        public virtual DbSet<userTypeTbl> userTypeTbl { get; set; }
        public virtual DbSet<generalDetailsActiveCandidate> generalDetailsActiveCandidate { get; set; }
    }
}
