//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Permissions
    {
        public string id { get; set; }
        public string password { get; set; }
        public int userType { get; set; }
    
        public virtual UserType UserType1 { get; set; }
        public virtual User_Profile User_Profile { get; set; }
    }
}
