//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant_Event
    {
        public int sn { get; set; }
        public string id_participant { get; set; }
        public string review { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User_Profile User_Profile { get; set; }
    }
}
