//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class scholar_bank_details
    {
        public string idScholar { get; set; }
        public int bank_name { get; set; }
        public int branch_number { get; set; }
        public int account_number { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual userTbl userTbl { get; set; }
    }
}
