//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scholarship_Student_Bank
    {
        public string idScholar { get; set; }
        public int bank_name { get; set; }
        public int branch_number { get; set; }
        public int account_number { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual User_Profile User_Profile { get; set; }
    }
}
