//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserProfile()
        {
            this.ContactStudents = new HashSet<ContactStudent>();
            this.ContactStudents1 = new HashSet<ContactStudent>();
            this.Files = new HashSet<File>();
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
            this.StudentScolarships = new HashSet<StudentScolarship>();
            this.StudentVolunteers = new HashSet<StudentVolunteer>();
            this.Events = new HashSet<Event>();
        }
    
        public string id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public int status { get; set; }
        public Nullable<int> yearsInTheProgram { get; set; }
        public string gender { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<int> cityNumber { get; set; }
        public string address { get; set; }
        public Nullable<int> numOfSiblings { get; set; }
        public Nullable<int> academicParents { get; set; }
        public string school { get; set; }
        public Nullable<int> yearFinishSchool { get; set; }
        public int typeOfService { get; set; }
        public Nullable<int> academicInstitution { get; set; }
        public Nullable<int> studyField { get; set; }
        public Nullable<int> startYear { get; set; }
        public Nullable<int> excpectedCompletionYear { get; set; }
        public string learningDisabilities { get; set; }
        public Nullable<int> psychometricGrade { get; set; }
        public string anotherScolarship { get; set; }
        public string educationFunding { get; set; }
        public string difficulties { get; set; }
        public Nullable<int> BankName { get; set; }
        public Nullable<int> numOfBank { get; set; }
        public Nullable<int> numAccount { get; set; }
        public Nullable<int> avergeDegree { get; set; }
        public Nullable<int> typeOfDegree { get; set; }
        public string comments { get; set; }
        public Nullable<int> averageSalaryFather { get; set; }
        public Nullable<int> averageSalaryMother { get; set; }
        public string roleInService { get; set; }
        public Nullable<int> easeOfService { get; set; }
        public Nullable<int> parentsDisability { get; set; }
        public Nullable<int> yearsInProgram { get; set; }
        public Nullable<int> residenceWhileStudiyng { get; set; }
        public string graduateJob { get; set; }
    
        public virtual AcademicInstitution AcademicInstitution1 { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactStudent> ContactStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactStudent> ContactStudents1 { get; set; }
        public virtual FieldOfStudy FieldOfStudy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
        public virtual loginAndPermission loginAndPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages1 { get; set; }
        public virtual Service Service { get; set; }
        public virtual Status Status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentScolarship> StudentScolarships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentVolunteer> StudentVolunteers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
    }
}
