//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Profile()
        {
            this.Contact_Candidate = new HashSet<Contact_Candidate>();
            this.Contact_Candidate1 = new HashSet<Contact_Candidate>();
            this.Deposits_scholarship = new HashSet<Deposits_scholarship>();
            this.Files = new HashSet<File>();
            this.Messages = new HashSet<Message>();
            this.Student_Volunteer = new HashSet<Student_Volunteer>();
            this.Students_Scholarship = new HashSet<Students_Scholarship>();
            this.Events = new HashSet<Event>();
        }
    
        public string id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public int status { get; set; }
        public Nullable<int> yearsInTheProgram { get; set; }
        public string gender { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<int> cityNumber { get; set; }
        public string address { get; set; }
        public Nullable<int> numOfSiblings { get; set; }
        public Nullable<int> academicParents { get; set; }
        public string school { get; set; }
        public Nullable<int> yearFinishSchool { get; set; }
        public int typeOfService { get; set; }
        public Nullable<int> academicInstitution { get; set; }
        public Nullable<int> studyField { get; set; }
        public Nullable<int> startYear { get; set; }
        public Nullable<int> excpectedCompletionYear { get; set; }
        public string anotherScholarship { get; set; }
        public string educationFunding { get; set; }
        public Nullable<int> typeOfDegree { get; set; }
        public string comments { get; set; }
        public string roleInService { get; set; }
        public Nullable<int> easeOfService { get; set; }
        public Nullable<int> residenceWhileStudiyng { get; set; }
        public string service_description { get; set; }
        public Nullable<double> averageDegree { get; set; }
    
        public virtual Academic_Institut Academic_Institut { get; set; }
        public virtual Active_Candidate_Info Active_Candidate_Info { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact_Candidate> Contact_Candidate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact_Candidate> Contact_Candidate1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deposits_scholarship> Deposits_scholarship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
        public virtual Login_Permissions Login_Permissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        public virtual Scholarship_Student_Bank Scholarship_Student_Bank { get; set; }
        public virtual Service Service { get; set; }
        public virtual Status Status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Volunteer> Student_Volunteer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students_Scholarship> Students_Scholarship { get; set; }
        public virtual Study_Field Study_Field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
    }
}
